### PR TITLE
Fix: align directive inline assembly on Darwin

### PR DESCRIPTION
**Pull request by Lqlsoftware**
Continue with issue #46, the `.align 16` directive inline assembly means different with Clang on Darwin and GCC on Linux.

In Clang of Darwin, `.align 16` means align with 2^16, which should be corrected with `.align 4`.

I've done plenty of test, showed that the performance problem is solved.

### CODE REVIEW

**Comment by Alcanderian** [comment]
Nice work :)!

I suggest to define a unify macro visible to the entire kernellib in
`src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/macros.h`
like:
```
#if defined(__APPLE__) && (defined(__GNUC__) || defined(__xlC__) || defined(__xlc__))
#define PPL_USE_X86_DARWIN
#endif
```
and
```
#if defined(__APPLE__) && (defined(__GNUC__) || defined(__xlC__) || defined(__xlc__))
#define PPL_X86_INLINE_ASM_ALIGN() ".align 4\n"
#else
#define PPL_X86_INLINE_ASM_ALIGN() ".align 16\n"
#endif
```

Maybe the latter is more acceptable

**Comment by Lqlsoftware** [comment]
Sure, this macro can also apply with #20.

**Comment by Lqlsoftware** [comment]
Done, I will do the same thing on repo ppl.common.

**Review by Alcanderian — APPROVED** [review]
Well done!😋

**Pull request merged**
