### PR TITLE
Fix compile error on MacOS (Darwin)

### PR DESCRIPTION
**Pull request by Lqlsoftware**
Some C++ 17 feature not supported in MacOS clang (Darwin), this PR contains some fix specify on Darwin.

### CODE REVIEW

**Comment by openppl-public** [comment]
Thanks for contributions :)

**Comment by Lqlsoftware** [comment]
My pleasure.
But it seems cannot pass the build test (before and after this commit):
```
[ RUN      ] TensorBufferInfoTest.with_buffer
[ERROR][2021-07-13 10:37:57.798][tensor_buffer_info.cc:59] TensorBufferInfo::SetDevice() failed: buffer is not empty
[ RUN      ] TensorImplTest.with_buffer
[ERROR][2021-07-12 20:38:52.229][tensor_buffer_info.cc:59] TensorBufferInfo::SetDevice() failed: buffer is not empty
```

**Comment by openppl-public** [comment]
> My pleasure.
> But it seems cannot pass the build test (before and after this commit):
> 
> ```
> [ RUN      ] TensorBufferInfoTest.with_buffer
> [ERROR][2021-07-13 10:37:57.798][tensor_buffer_info.cc:59] TensorBufferInfo::SetDevice() failed: buffer is not empty
> [ RUN      ] TensorImplTest.with_buffer
> [ERROR][2021-07-12 20:38:52.229][tensor_buffer_info.cc:59] TensorBufferInfo::SetDevice() failed: buffer is not empty
> ```

These are abnormal tests that are used to test whether pplnn can handle exceptions as correctly.

```
[----------] Global test environment tear-down
[==========] 69 tests from 18 test suites ran. (32 ms total)
[  PASSED  ] 69 tests.
```

All unittests are passed.

**Comment by Lqlsoftware** [comment]
Got it, nice work :)

**Pull request merged**
